version: "3.9"

services:
  bundler:
    container_name: bundler-scroll
    build: .
    restart: unless-stopped
    ports:
      - 10012:4337
    volumes:
      - .env-scroll:/app/.env
    environment:
      - TZ=Asia/Shanghai
