version: "3.9"

services:
  bundler-1:
    container_name: bundler-arbitrum-mainnet-v1.2-1
    build: .
    restart: unless-stopped
    ports:
      - 10276:4337
    volumes:
      - .env-arbitrum-mainnet-1:/app/.env
    environment:
      - TZ=Asia/Shanghai
  bundler-2:
    container_name: bundler-arbitrum-mainnet-v1.2-2
    build: .
    restart: unless-stopped
    ports:
      - 10277:4337
    volumes:
      - .env-arbitrum-mainnet-2:/app/.env
    environment:
      - TZ=Asia/Shanghai
  bundler-3:
    container_name: bundler-arbitrum-mainnet-v1.2-3
    build: .
    restart: unless-stopped
    ports:
      - 10278:4337
    volumes:
      - .env-arbitrum-mainnet-3:/app/.env
    environment:
      - TZ=Asia/Shanghai
